
 
const sampleListings = [

  {
    title: "Hawaii Oceanfront Villa",
    description: "Relax in paradise with ocean breeze and volcano views.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    price: 5800,
    location: "Maui",
    country: "United States",
  },
  {
    title: "Sydney Harbour View Hotel",
    description: "Stay near the Sydney Opera House with waterfront luxury.",
    image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=800&q=60",
    price: 4500,
    location: "Sydney",
    country: "Australia",
  },
  {
    title: "Queenstown Lake Lodge",
    description: "Luxury alpine lodge with adventure activities nearby.",
    image: "https://images.unsplash.com/photo-1493558103817-58b2924bce98?auto=format&fit=crop&w=800&q=60",
    price: 3800,
    location: "Queenstown",
    country: "New Zealand",
  },
  {
    title: "Singapore Marina View Hotel",
    description: "Elegant city hotel with panoramic skyline and bay views.",
    image: "https://images.unsplash.com/photo-1554189097-ffe88e998a2b?auto=format&fit=crop&w=800&q=60",
    price: 4100,
    location: "Marina Bay",
    country: "Singapore",
  },
 
  {
    title: "Vienna Imperial Palace Hotel",
    description: "Historic hotel with royal architecture and central city access.",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=60",
    price: 2900,
    location: "Vienna",
    country: "Austria",
  },
  {
    title: "Berlin Modern Loft",
    description: "Stylish city stay with industrial design and great nightlife.",
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=60",
    price: 2600,
    location: "Berlin",
    country: "Germany",
  },
  {
    title: "London Riverfront Suites",
    description: "Elegant suites with Thames River views and English hospitality.",
    image: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=60",
    price: 5000,
    location: "London",
    country: "United Kingdom",
  },
  {
    title: "Iceland Northern Lights Lodge",
    description: "Glass-roof cabins designed for stargazing and aurora watching.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    price: 4200,
    location: "Reykjavik",
    country: "Iceland",
  },
  {
    title: "Cairo Nile View Hotel",
    description: "Stay by the Nile River with easy access to the Great Pyramids.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Cairo",
    country: "Egypt",
  },
  {
    title: "Kenya Safari Lodge",
    description: "Luxury lodge offering wildlife safaris and breathtaking savanna sunsets.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=60",
    price: 3900,
    location: "Maasai Mara",
    country: "Kenya",
  },
  {
    title: "Bora Bora Lagoon Villa",
    description: "Iconic overwater bungalows surrounded by crystal-clear blue lagoons.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    price: 9500,
    location: "Bora Bora",
    country: "French Polynesia",
  },
  {
    title: "Helsinki Nordic Glasshouse",
    description: "Scandinavian glasshouse retreat surrounded by snow and pine forests.",
    image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=60",
    price: 3100,
    location: "Helsinki",
    country: "Finland",
  },
  {
    title: "Lisbon Riverside Hotel",
    description: "Elegant Portuguese stay near the riverfront with tiled courtyards.",
    image: "https://images.unsplash.com/photo-1563911302283-d2bc129e7570?auto=format&fit=crop&w=800&q=60",
    price: 2700,
    location: "Lisbon",
    country: "Portugal",
  },
  {
    title: "Croatia Adriatic Villa",
    description: "Mediterranean villa perched above turquoise Adriatic waters.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    price: 3300,
    location: "Dubrovnik",
    country: "Croatia",
  },  {
    title: "Modern Loft in Downtown",
    description:
      "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image:
      "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    price: 1200,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Mountain Retreat",
    description:
      "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image:
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=60",
    price: 1000,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Historic Villa in Tuscany",
    description:
      "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image:
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Florence",
    country: "Italy",
  },
  {
    title: "Secluded Treehouse Getaway",
    description:
      "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image:
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=60",
    price: 800,
    location: "Portland",
    country: "United States",
  },
  {
    title: "Luxury Penthouse with City Views",
    description:
      "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image:
      "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description:
      "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image:
      "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
  },
  {
    title: "Safari Lodge in the Serengeti",
    description:
      "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image:
      "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=60",
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=800&q=60",
    price: 1500,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    price: 1200,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=60",
    price: 1000,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Florence",
    country: "Italy",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=60",
    price: 800,
    location: "Portland",
    country: "United States",
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=60",
    price: 2000,
    location: "Cancun",
    country: "Mexico",
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=60",
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
  },
  {
    title: "Desert Glamping Dome",
    description: "Enjoy the magic of the desert in this luxury glamping dome with stargazing views.",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
    price: 1100,
    location: "Dubai",
    country: "UAE",
  },
  {
    title: "Charming Farmhouse Stay",
    description: "Escape city life and stay in this peaceful countryside farmhouse.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=60",
    price: 950,
    location: "Punjab",
    country: "India",
  },
  {
    title: "Luxury Yacht Experience",
    description: "Sail away in luxury with this private yacht rental for a dreamy vacation.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    price: 6000,
    location: "Miami",
    country: "United States",
  },
  {
    title: "Countryside Castle",
    description: "Stay like royalty in this restored medieval castle with modern comforts.",
    image: "https://images.unsplash.com/photo-1529429617124-95b109e86bb8?auto=format&fit=crop&w=800&q=60",
    price: 5000,
    location: "Edinburgh",
    country: "Scotland",
  },
  {
    title: "Jungle Eco Lodge",
    description: "Connect with nature in this eco-friendly jungle lodge with wildlife tours.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Bali",
    country: "Indonesia",
  },
  {
    title: "Icelandic Glass Igloo",
    description: "Watch the northern lights from the comfort of your own glass igloo.",
    image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=60",
    price: 2700,
    location: "Reykjavik",
    country: "Iceland",
  },
  {
    title: "Parisian Studio Apartment",
    description: "A chic studio in the heart of Paris, steps away from the Eiffel Tower.",
    image: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=60",
    price: 2200,
    location: "Paris",
    country: "France",
  },
  {
    title: "Tokyo Capsule Hotel",
    description: "Experience Japan’s unique capsule stay in the center of Tokyo.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    price: 700,
    location: "Tokyo",
    country: "Japan",
  },
  {
    title: "Santorini Cliffside Villa",
    description: "Soak in breathtaking sunsets from this cliffside villa overlooking the sea.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    price: 3200,
    location: "Santorini",
    country: "Greece",
    
  },
];



module.exports = { data: sampleListings };


